// <auto-generated />
using System;
using DownCare.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DownCare.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250513000300_updateActivityData")]
    partial class updateActivityData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoctorMom", b =>
                {
                    b.Property<string>("DoctorsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MomsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DoctorsId", "MomsId");

                    b.HasIndex("MomsId");

                    b.ToTable("DoctorMom");
                });

            modelBuilder.Entity("DownCare.Core.Entities.ActivityData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoundPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivitiyData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "/Images/OneWord/أرنب.jpg",
                            Label = "أرنب",
                            SoundPath = "/Sound/OneWord/ارنب.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "/Images/OneWord/استيكه.png",
                            Label = "استيكه",
                            SoundPath = "/Sound/OneWord/استيكة.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "/Images/OneWord/أسد.jpg",
                            Label = "أسد",
                            SoundPath = "/Sound/OneWord/اسد.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "/Images/OneWord/أسنان.jpg",
                            Label = "أسنان",
                            SoundPath = "/Sound/OneWord/اسنان.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "/Images/OneWord/برايه.png",
                            Label = "برايه",
                            SoundPath = "/Sound/OneWord/برايه.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "/Images/OneWord/بطاطس.jpg",
                            Label = "بطاطس",
                            SoundPath = "/Sound/OneWord/بطاطس.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "/Images/OneWord/بطة.jpg",
                            Label = "بطة",
                            SoundPath = "/Sound/OneWord/بطة.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "/Images/OneWord/بنت.jpg",
                            Label = "بنت",
                            SoundPath = "/Sound/OneWord/بنت.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "/Images/OneWord/تفاحة.jpg",
                            Label = "تفاحة",
                            SoundPath = "/Sound/OneWord/تفاحة.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 10,
                            ImagePath = "/Images/OneWord/جزر.jpg",
                            Label = "جزر",
                            SoundPath = "/Sound/OneWord/جزر.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 11,
                            ImagePath = "/Images/OneWord/جمل.jpg",
                            Label = "جمل",
                            SoundPath = "/Sound/OneWord/جمل.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 12,
                            ImagePath = "/Images/OneWord/حصان.jpg",
                            Label = "حصان",
                            SoundPath = "/Sound/OneWord/حصان.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 13,
                            ImagePath = "/Images/OneWord/حلة.png",
                            Label = "حلة",
                            SoundPath = "/Sound/OneWord/حلة.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 14,
                            ImagePath = "/Images/OneWord/خروف.jpg",
                            Label = "خروف",
                            SoundPath = "/Sound/OneWord/خروف.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 15,
                            ImagePath = "/Images/OneWord/خيار.jpg",
                            Label = "خيار",
                            SoundPath = "/Sound/OneWord/خيار.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 16,
                            ImagePath = "/Images/OneWord/سكينة.jpg",
                            Label = "سكينة",
                            SoundPath = "/Sound/OneWord/سكينة.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 17,
                            ImagePath = "/Images/OneWord/سمكة.jpg",
                            Label = "سمكة",
                            SoundPath = "/Sound/OneWord/سمكة.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 18,
                            ImagePath = "/Images/OneWord/شنطه.png",
                            Label = "شنطه",
                            SoundPath = "/Sound/OneWord/شنطه.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 19,
                            ImagePath = "/Images/OneWord/شوكة.jpg",
                            Label = "شوكة",
                            SoundPath = "/Sound/OneWord/شوكة.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 20,
                            ImagePath = "/Images/OneWord/عين.jpg",
                            Label = "عين",
                            SoundPath = "/Sound/OneWord/عين.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 21,
                            ImagePath = "/Images/OneWord/غزالة.jpg",
                            Label = "غزالة",
                            SoundPath = "/Sound/OneWord/غزالة.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 22,
                            ImagePath = "/Images/OneWord/فراولة.jpg",
                            Label = "فراولة",
                            SoundPath = "/Sound/OneWord/فراولة.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 23,
                            ImagePath = "/Images/OneWord/فيل.jpg",
                            Label = "فيل",
                            SoundPath = "/Sound/OneWord/فيل.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 24,
                            ImagePath = "/Images/OneWord/كتاب.png",
                            Label = "كتاب",
                            SoundPath = "/Sound/OneWord/كتاب.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 25,
                            ImagePath = "/Images/OneWord/كراسه.png",
                            Label = "كراسه",
                            SoundPath = "/Sound/OneWord/كراسه.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 26,
                            ImagePath = "/Images/OneWord/كلب.jpg",
                            Label = "كلب",
                            SoundPath = "/Sound/OneWord/كلب.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 27,
                            ImagePath = "/Images/OneWord/لسان.jpg",
                            Label = "لسان",
                            SoundPath = "/Sound/OneWord/لسان.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 28,
                            ImagePath = "/Images/OneWord/ولد.jpg",
                            Label = "ولد",
                            SoundPath = "/Sound/OneWord/ولد.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 29,
                            ImagePath = "/Images/OneWord/منجا.png",
                            Label = "مانجا",
                            SoundPath = "/Sound/OneWord/منجا.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 30,
                            ImagePath = "/Images/OneWord/موز.png",
                            Label = "موز",
                            SoundPath = "/Sound/OneWord/موز.mp3",
                            Type = "OneWord"
                        },
                        new
                        {
                            Id = 31,
                            ImagePath = "/Images/TwoWord/الولد يكتب.jpg",
                            Label = "الولد يكتب",
                            SoundPath = "/Sound/TwoWord/الولد يكتب.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 32,
                            ImagePath = "/Images/TwoWord/الولد ينام.jpg",
                            Label = "الولد ينام",
                            SoundPath = "/Sound/TwoWord/الولد ينام.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 33,
                            ImagePath = "/Images/TwoWord/أجرى بسرعة.jpg",
                            Label = "أجرى بسرعة",
                            SoundPath = "/Sound/TwoWord/أجرى بسرعة.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 34,
                            ImagePath = "/Images/TwoWord/أذهب للمدرسة.jpg",
                            Label = "أذهب للمدرسة",
                            SoundPath = "/Sound/TwoWord/أذهب للمدرسة.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 35,
                            ImagePath = "/Images/TwoWord/أركب الدراجة.jpg",
                            Label = "أركب الدراجة",
                            SoundPath = "/Sound/TwoWord/أركب الدراجة.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 36,
                            ImagePath = "/Images/TwoWord/أساعد أمى.jpg",
                            Label = "أساعد أمى",
                            SoundPath = "/Sound/TwoWord/أساعد أمى.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 37,
                            ImagePath = "/Images/TwoWord/استيقظ مبكرا.jpg",
                            Label = "استيقظ مبكرا",
                            SoundPath = "/Sound/TwoWord/أستيقظ مبكرا.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 38,
                            ImagePath = "/Images/TwoWord/أشاهد التليفزيون.jpg",
                            Label = "أشاهد التليفزيون",
                            SoundPath = "/Sound/TwoWord/أشاهد التليفزيون.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 39,
                            ImagePath = "/Images/TwoWord/أغسل اسنانى.jpg",
                            Label = "أغسل اسنانى",
                            SoundPath = "/Sound/TwoWord/أغسل أسنانى.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 40,
                            ImagePath = "/Images/TwoWord/أغنى أغنية.jpg",
                            Label = "أغنى أغنية",
                            SoundPath = "/Sound/TwoWord/أغنى أغنية.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 41,
                            ImagePath = "/Images/TwoWord/أقرأ كتاب.jpg",
                            Label = "أقرأ كتاب",
                            SoundPath = "/Sound/TwoWord/أقرأ كتاب.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 42,
                            ImagePath = "/Images/TwoWord/حديقة الحيوان.jpg",
                            Label = "حديقة الحيوان",
                            SoundPath = "/Sound/TwoWord/حديقة الحيوان.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 43,
                            ImagePath = "/Images/TwoWord/أكتب الواجب.jpg",
                            Label = "أكتب الواجب",
                            SoundPath = "/Sound/TwoWord/أكتب الواجب.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 44,
                            ImagePath = "/Images/TwoWord/أكل سندوتش.jpg",
                            Label = "أكل سندوتش",
                            SoundPath = "/Sound/TwoWord/أكل سندوتش.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 45,
                            ImagePath = "/Images/TwoWord/الأسد يزئر.jpg",
                            Label = "الأسد يزئر",
                            SoundPath = "/Sound/TwoWord/الأسد يزئر.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 46,
                            ImagePath = "/Images/TwoWord/ألبس ملابسى.jpg",
                            Label = "ألبس ملابسى",
                            SoundPath = "/Sound/TwoWord/ألبس ملابسى.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 47,
                            ImagePath = "/Images/TwoWord/البطة تسبح.jpg",
                            Label = "البطة تسبح",
                            SoundPath = "/Sound/TwoWord/البطة تسبح.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 48,
                            ImagePath = "/Images/TwoWord/البنت تطبخ.jpg",
                            Label = "البنت تطبخ",
                            SoundPath = "/Sound/TwoWord/البنت تطبخ.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 49,
                            ImagePath = "/Images/TwoWord/الحصان سريع.jpg",
                            Label = "الحصان سريع",
                            SoundPath = "/Sound/TwoWord/الحصان سريع.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 50,
                            ImagePath = "/Images/TwoWord/الدب كبير.jpg",
                            Label = "الدب كبير",
                            SoundPath = "/Sound/TwoWord/الدب كبير.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 51,
                            ImagePath = "/Images/TwoWord/الزرافة طويلة.jpg",
                            Label = "الزرافة طويلة",
                            SoundPath = "/Sound/TwoWord/الزرافة طويلة.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 52,
                            ImagePath = "/Images/TwoWord/ألعب بالكرة.jpg",
                            Label = "ألعب بالكرة",
                            SoundPath = "/Sound/TwoWord/ألعب بالكرة.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 53,
                            ImagePath = "/Images/TwoWord/الفيل ضخم.jpg",
                            Label = "الفيل ضخم",
                            SoundPath = "/Sound/TwoWord/الفيل ضخم.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 54,
                            ImagePath = "/Images/TwoWord/الولد يأكل.jpg",
                            Label = "الولد يأكل",
                            SoundPath = "/Sound/TwoWord/الولد يأكل.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 55,
                            ImagePath = "/Images/TwoWord/الولد يذاكر.jpg",
                            Label = "الولد يذاكر",
                            SoundPath = "/Sound/TwoWord/الولد يذاكر.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 56,
                            ImagePath = "/Images/TwoWord/الولد يرسم.jpg",
                            Label = "الولد يرسم",
                            SoundPath = "/Sound/TwoWord/الولد يرسم.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 57,
                            ImagePath = "/Images/TwoWord/الولد يزرع.jpg",
                            Label = "الولد يزرع",
                            SoundPath = "/Sound/TwoWord/الولد يزرع.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 58,
                            ImagePath = "/Images/TwoWord/الولد يسبح.jpg",
                            Label = "الولد يسبح",
                            SoundPath = "/Sound/TwoWord/الولد يسبح.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 59,
                            ImagePath = "/Images/TwoWord/الولد يشرب.jpg",
                            Label = "الولد يشرب",
                            SoundPath = "/Sound/TwoWord/الولد يشرب.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 60,
                            ImagePath = "/Images/TwoWord/الولد يصطاد.jpg",
                            Label = "الولد يصطاد",
                            SoundPath = "/Sound/TwoWord/الولد يصطاد.mp3",
                            Type = "TwoWord"
                        },
                        new
                        {
                            Id = 61,
                            ImagePath = "/Images/ThreeWord/اسرح شعري بالمشط.jpg",
                            Label = "اسرح شعري بالمشط",
                            SoundPath = "/Sound/ThreeWord/اسرح شعري بالمشط.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 62,
                            ImagePath = "/Images/ThreeWord/الولد يلعب بالكرة.jpg",
                            Label = "الولد يلعب بالكرة",
                            SoundPath = "/Sound/ThreeWord/الولد يلعب بالكرة.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 63,
                            ImagePath = "/Images/ThreeWord/اشرب عصير برتقان.jpg",
                            Label = "اشرب عصير برتقان",
                            SoundPath = "/Sound/ThreeWord/اشرب عصير برتقان.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 64,
                            ImagePath = "/Images/ThreeWord/اغسل يدي بالماء.png",
                            Label = "اغسل يدي بالماء",
                            SoundPath = "/Sound/ThreeWord/اغسل يدي بالماء.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 65,
                            ImagePath = "/Images/ThreeWord/الأرنب يحب الجزر.png",
                            Label = "الأرنب يحب الجزر",
                            SoundPath = "/Sound/ThreeWord/الأرنب يحب الجزر.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 66,
                            ImagePath = "/Images/ThreeWord/الاطفال يلعبون بالكره.jpg",
                            Label = "الاطفال يلعبون بالكره",
                            SoundPath = "/Sound/ThreeWord/الاطفال يلعبون بالكره.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 67,
                            ImagePath = "/Images/ThreeWord/البقرة تأكل العشب.jpg",
                            Label = "البقرة تأكل العشب",
                            SoundPath = "/Sound/ThreeWord/البقرة تأكل العشب.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 68,
                            ImagePath = "/Images/ThreeWord/البنت بتعمل الواجب.png",
                            Label = "البنت بتعمل الواجب",
                            SoundPath = "/Sound/ThreeWord/البنت بتعمل الواجب.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 69,
                            ImagePath = "/Images/ThreeWord/البنت بتلعب الموسيقى.png",
                            Label = "البنت بتلعب الموسيقى",
                            SoundPath = "/Sound/ThreeWord/البنت بتلعب الموسيقى.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 70,
                            ImagePath = "/Images/ThreeWord/البنت تشرب العصير.jpg",
                            Label = "البنت تشرب العصير",
                            SoundPath = "/Sound/ThreeWord/البنت تشرب العصير.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 71,
                            ImagePath = "/Images/ThreeWord/البنت تقرأ كتاب.png",
                            Label = "البنت تقرأ كتاب",
                            SoundPath = "/Sound/ThreeWord/البنت تقرأ كتاب.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 72,
                            ImagePath = "/Images/ThreeWord/القطه تأكل السمك.png",
                            Label = "القطه تأكل السمك",
                            SoundPath = "/Sound/ThreeWord/القطه تأكل السمك.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 73,
                            ImagePath = "/Images/ThreeWord/الكلب يأكل العظم.png",
                            Label = "الكلب يأكل العظم",
                            SoundPath = "/Sound/ThreeWord/الكلب يأكل العظم.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 74,
                            ImagePath = "/Images/ThreeWord/الولد والبنت بيلعبوا.jpg",
                            Label = "الولد والبنت بيلعبوا",
                            SoundPath = "/Sound/ThreeWord/الولد والبنت بيلعبوا.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 75,
                            ImagePath = "/Images/ThreeWord/الولد يأكل الطعام.png",
                            Label = "الولد يأكل الطعام",
                            SoundPath = "/Sound/ThreeWord/الولد يأكل الطعام.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 76,
                            ImagePath = "/Images/ThreeWord/الولد يجري بسرعة.jpg",
                            Label = "الولد يجري بسرعة",
                            SoundPath = "/Sound/ThreeWord/الولد يجري بسرعة.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 77,
                            ImagePath = "/Images/ThreeWord/الولد يحب الحيوانات.jpg",
                            Label = "الولد يحب الحيوانات",
                            SoundPath = "/Sound/ThreeWord/الولد يحب الحيوانات.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 78,
                            ImagePath = "/Images/ThreeWord/الولد يذهب للمدرسه.png",
                            Label = "الولد يذهب للمدرسه",
                            SoundPath = "/Sound/ThreeWord/الولد يذهب للمدرسة.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 79,
                            ImagePath = "/Images/ThreeWord/الولد يرسم المنزل.png",
                            Label = "الولد يرسم المنزل",
                            SoundPath = "/Sound/ThreeWord/الولد يرسم المنزل.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 80,
                            ImagePath = "/Images/ThreeWord/الولد يزرع شجرة.jpg",
                            Label = "الولد يزرع شجرة",
                            SoundPath = "/Sound/ThreeWord/الولد يزرع شجرة.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 81,
                            ImagePath = "/Images/ThreeWord/الولد يشرب الماء.png",
                            Label = "الولد يشرب الماء",
                            SoundPath = "/Sound/ThreeWord/الولد يشرب الماء.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 82,
                            ImagePath = "/Images/ThreeWord/الولد يصطاد السمك.png",
                            Label = "الولد يصطاد السمك",
                            SoundPath = "/Sound/ThreeWord/الولد يصطاد السمك.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 83,
                            ImagePath = "/Images/ThreeWord/الولد يغسل اسنانه.png",
                            Label = "الولد يغسل اسنانه",
                            SoundPath = "/Sound/ThreeWord/الولد يغسل اسنانه.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 84,
                            ImagePath = "/Images/ThreeWord/الولد يلبس البنطلون.jpg",
                            Label = "الولد يلبس البنطلون",
                            SoundPath = "/Sound/ThreeWord/الولد يلبس البنطلون.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 85,
                            ImagePath = "/Images/ThreeWord/الولد يلبس القميص.jpg",
                            Label = "الولد يلبس القميص",
                            SoundPath = "/Sound/ThreeWord/الولد يلبس القميص.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 86,
                            ImagePath = "/Images/ThreeWord/الولد يلعب المرجيحه.jpg",
                            Label = "الولد يلعب المرجيحه",
                            SoundPath = "/Sound/ThreeWord/الولد يلعب المرجيحه.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 87,
                            ImagePath = "/Images/ThreeWord/تغسل امى الملابس.jpg",
                            Label = "تغسل امى الملابس",
                            SoundPath = "/Sound/ThreeWord/تغسل امى الملابس.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 88,
                            ImagePath = "/Images/ThreeWord/البنت تلعب بالعروسة.png",
                            Label = "البنت تلعب بالعروسة",
                            SoundPath = "/Sound/ThreeWord/البنت تلعب بالعروسة.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 89,
                            ImagePath = "/Images/ThreeWord/الاستحمام بالماء منعش.jpg",
                            Label = "الاستحمام بالماء منعش",
                            SoundPath = "/Sound/ThreeWord/الاستحمام بالماء منعش.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 90,
                            ImagePath = "/Images/ThreeWord/ما اجمل النوم.jpg",
                            Label = "ما اجمل النوم",
                            SoundPath = "/Sound/ThreeWord/ما اجمل النوم.mp3",
                            Type = "ThreeWord"
                        },
                        new
                        {
                            Id = 91,
                            ImagePath = "/Images/FourWord/استحم بالماء والصابون والشامبو.jpg",
                            Label = "استحم بالماء والصابون والشامبو",
                            SoundPath = "/Sound/FourWord/استحم بالماء والصابون والشامبو.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 92,
                            ImagePath = "/Images/FourWord/أسرح شعرى بالفرشاة والزيت.png",
                            Label = "أسرح شعرى بالفرشاة والزيت",
                            SoundPath = "/Sound/FourWord/أسرح شعرى بالفرشاة والزيت.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 93,
                            ImagePath = "/Images/FourWord/اغسل اسنانى بالفرشاة والمعجون.png",
                            Label = "اغسل اسنانى بالفرشاة والمعجون",
                            SoundPath = "/Sound/FourWord/اغسل اسنانى بالفرشاة والمعجون.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 94,
                            ImagePath = "/Images/FourWord/اغسل يدي بالماء والصابون.png",
                            Label = "اغسل يدي بالماء والصابون",
                            SoundPath = "/Sound/FourWord/اغسل يدي بالماء والصابون.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 95,
                            ImagePath = "/Images/FourWord/الاب بيزعق لابنه غاضبا.png",
                            Label = "الاب بيزعق لابنه غاضبا",
                            SoundPath = "/Sound/FourWord/الاب بيزعق لابنه غاضبا.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 96,
                            ImagePath = "/Images/FourWord/الاب يعطي ابنته هديه.png",
                            Label = "الاب يعطي ابنته هديه",
                            SoundPath = "/Sound/FourWord/الاب يعطي ابنته هديه.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 97,
                            ImagePath = "/Images/FourWord/الاطفال يلعبون على الشاطئ.jpg",
                            Label = "الاطفال يلعبون على الشاطئ",
                            SoundPath = "/Sound/FourWord/الاطفال يلعبون على الشاطئ.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 98,
                            ImagePath = "/Images/FourWord/الأولاد يلعبون فى الحديقة.png",
                            Label = "الأولاد يلعبون فى الحديقة",
                            SoundPath = "/Sound/FourWord/الأولاد يلعبون فى الحديقة.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 99,
                            ImagePath = "/Images/FourWord/البنت ترسم شمس وورود.png",
                            Label = "البنت ترسم شمس وورود",
                            SoundPath = "/Sound/FourWord/البنت ترسم شمس وورود.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 100,
                            ImagePath = "/Images/FourWord/البنت تساعد امها بالمطبخ.jpg",
                            Label = "البنت تساعد امها بالمطبخ",
                            SoundPath = "/Sound/FourWord/البنت تساعد امها بالمطبخ.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 101,
                            ImagePath = "/Images/FourWord/البنت تلعب مع الكلب.png",
                            Label = "البنت تلعب مع الكلب",
                            SoundPath = "/Sound/FourWord/البنت تلعب مع الكلب.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 102,
                            ImagePath = "/Images/FourWord/السمك يعيش فى الماء.png",
                            Label = "السمك يعيش فى الماء",
                            SoundPath = "/Sound/FourWord/السمك يعيش فى الماء.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 103,
                            ImagePath = "/Images/FourWord/الطبيب يعطي المريض حقنة.png",
                            Label = "الطبيب يعطي المريض حقنة",
                            SoundPath = "/Sound/FourWord/الطبيب يعطي المريض حقنة.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 104,
                            ImagePath = "/Images/FourWord/الطفل يقرأ الكتاب بأهتمام.png",
                            Label = "الطفل يقرأ الكتاب بأهتمام",
                            SoundPath = "/Sound/FourWord/الطفل يقرأ الكتاب بأهتمام.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 105,
                            ImagePath = "/Images/FourWord/العائلة كلها تساعد الام.jpg",
                            Label = "العائلة كلها تساعد الام",
                            SoundPath = "/Sound/FourWord/العائلة كلها تساعد الام.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 106,
                            ImagePath = "/Images/FourWord/ألعب الكرة مع الاصدقاء.jpg",
                            Label = "ألعب الكرة مع الاصدقاء",
                            SoundPath = "/Sound/FourWord/ألعب الكرة مع الاصدقاء.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 107,
                            ImagePath = "/Images/FourWord/ألعب بالألعاب مع اختى.png",
                            Label = "ألعب بالألعاب مع اختى",
                            SoundPath = "/Sound/FourWord/ألعب بالألعاب مع اختى.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 108,
                            ImagePath = "/Images/FourWord/المستشفى مكان لعلاج المرضى.jpg",
                            Label = "المستشفى مكان لعلاج المرضى",
                            SoundPath = "/Sound/FourWord/المستشفى مكان لعلاج المرضى.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 109,
                            ImagePath = "/Images/FourWord/المعلمة تقرأ قصة للأطفال.jpg",
                            Label = "المعلمة تقرأ قصة للأطفال",
                            SoundPath = "/Sound/FourWord/المعلمة تقرأ قصة للأطفال.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 110,
                            ImagePath = "/Images/FourWord/الولد يساعد امه ف التنظيف.jpg",
                            Label = "الولد يساعد امه ف التنظيف",
                            SoundPath = "/Sound/FourWord/الولد يساعد امه ف التنظيف.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 111,
                            ImagePath = "/Images/FourWord/الولد يسبح فى البحر.jpg",
                            Label = "الولد يسبح فى البحر",
                            SoundPath = "/Sound/FourWord/الولد يسبح فى البحر.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 112,
                            ImagePath = "/Images/FourWord/الولد يشرب عصير برتقان.png",
                            Label = "الولد يشرب عصير برتقان",
                            SoundPath = "/Sound/FourWord/الولد يشرب عصير برتقان.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 113,
                            ImagePath = "/Images/FourWord/الولد يصطاد السمك بالصنارة.png",
                            Label = "الولد يصطاد السمك بالصنارة",
                            SoundPath = "/Sound/FourWord/الولد يصطاد السمك بالصنارة.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 114,
                            ImagePath = "/Images/FourWord/الولد يغسل اسنانة بالفرشاة.png",
                            Label = "الولد يغسل اسنانة بالفرشاة",
                            SoundPath = "/Sound/FourWord/الولد يغسل اسنانة بالفرشاة.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 115,
                            ImagePath = "/Images/FourWord/الولد يلعب مع القطه.png",
                            Label = "الولد يلعب مع القطه",
                            SoundPath = "/Sound/FourWord/الولد يلعب مع القطه.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 116,
                            ImagePath = "/Images/FourWord/انا واختى نقرأ الكتب.png",
                            Label = "انا واختى نقرأ الكتب",
                            SoundPath = "/Sound/FourWord/انا واختى نقرأ الكتب.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 117,
                            ImagePath = "/Images/FourWord/تسقي البنت الازهار الجميلة.png",
                            Label = "تسقي البنت الازهار الجميلة",
                            SoundPath = "/Sound/FourWord/تسقي البنت الازهار الجميلة.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 118,
                            ImagePath = "/Images/FourWord/تشرح المعلمة الدرس جيدا.png",
                            Label = "تشرح المعلمة الدرس جيدا",
                            SoundPath = "/Sound/FourWord/تشرح المعلمة الدرس جيدا.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 119,
                            ImagePath = "/Images/FourWord/تغسل البنت التفاح بالماء.png",
                            Label = "تغسل البنت التفاح بالماء",
                            SoundPath = "/Sound/FourWord/تغسل البنت التفاح بالماء.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 120,
                            ImagePath = "/Images/FourWord/ما اجمل قراءة الكتب.png",
                            Label = "ما اجمل قراءة الكتب",
                            SoundPath = "/Sound/FourWord/ما اجمل قراءة الكتب.mp3",
                            Type = "FourWord"
                        },
                        new
                        {
                            Id = 121,
                            ImagePath = "/Images/FiveWord/أذهب الى المدرسة مع اصحابي.jpg",
                            Label = "أذهب الى المدرسة مع اصحابي",
                            SoundPath = "/Sound/FiveWord/أذهب الى المدرسة مع اصحابي.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 122,
                            ImagePath = "/Images/FiveWord/اشارة المرور حمرة و صفرة وخضرة.png",
                            Label = "اشارة المرور حمرة و صفرة وخضرة",
                            SoundPath = "/Sound/FiveWord/اشارة المرور حمرة و صفرة وخضرة.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 123,
                            ImagePath = "/Images/FiveWord/البنت بتاكل فاكهة وسندوتش وتشرب عصير.png",
                            Label = "البنت بتاكل فاكهة وسندوتش وتشرب عصير",
                            SoundPath = "/Sound/FiveWord/البنت بتاكل فاكهة وسندوتش وتشرب عصير.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 124,
                            ImagePath = "/Images/FiveWord/البنت ترسم شمس و ورود بالألوان.png",
                            Label = "البنت ترسم شمس و ورود بالألوان",
                            SoundPath = "/Sound/FiveWord/البنت ترسم شمس و ورود بالألوان.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 125,
                            ImagePath = "/Images/FiveWord/البنت تسقى الأزهار فى الصبح.png",
                            Label = "البنت تسقى الأزهار فى الصبح",
                            SoundPath = "/Sound/FiveWord/البنت تسقى الأزهار فى الصبح.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 126,
                            ImagePath = "/Images/FiveWord/الجزار يقطع اللحم قطع بالسكينة.png",
                            Label = "الجزار يقطع اللحم قطع بالسكينة",
                            SoundPath = "/Sound/FiveWord/الجزار يقطع اللحم قطع بالسكينة.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 127,
                            ImagePath = "/Images/FiveWord/السواق يقود الاتوبيس على الطريق.jpg",
                            Label = "السواق يقود الاتوبيس على الطريق",
                            SoundPath = "/Sound/FiveWord/السواق يقود الاتوبيس على الطريق.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 128,
                            ImagePath = "/Images/FiveWord/الشمس تنور السما فى النهار.jpg",
                            Label = "الشمس تنور السما فى النهار",
                            SoundPath = "/Sound/FiveWord/الشمس تنور السما فى النهار.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 129,
                            ImagePath = "/Images/FiveWord/الطفل يتفرج الكارتون على التليفزيون.png",
                            Label = "الطفل يتفرج الكارتون على التليفزيون",
                            SoundPath = "/Sound/FiveWord/الطفل يتفرج الكارتون على التليفزيون.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 130,
                            ImagePath = "/Images/FiveWord/الطيار يقود الطيارة فى السما.png",
                            Label = "الطيار يقود الطيارة فى السما",
                            SoundPath = "/Sound/FiveWord/الطيار يقود الطيارة فى السما.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 131,
                            ImagePath = "/Images/FiveWord/الطيور تطير فى السما الزرقا.jpg",
                            Label = "الطيور تطير فى السما الزرقا",
                            SoundPath = "/Sound/FiveWord/الطيور تطير فى السما الزرقا.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 132,
                            ImagePath = "/Images/FiveWord/ألعب الكرة مع اصحابي فى الملعب.jpg",
                            Label = "ألعب الكرة مع اصحابي فى الملعب",
                            SoundPath = "/Sound/FiveWord/ألعب الكرة مع اصحابي فى الملعب.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 133,
                            ImagePath = "/Images/FiveWord/الفراشات تطير حول الأزهار الجميلة.jpg",
                            Label = "الفراشات تطير حول الأزهار الجميلة",
                            SoundPath = "/Sound/FiveWord/الفراشات تطير حول الأزهار الجميلة.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 134,
                            ImagePath = "/Images/FiveWord/الفلاح يحصد القمح من الحقل.jpg",
                            Label = "الفلاح يحصد القمح من الحقل",
                            SoundPath = "/Sound/FiveWord/الفلاح يحصد القمح من الحقل.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 135,
                            ImagePath = "/Images/FiveWord/القمر ينور السما فى الليل.jpg",
                            Label = "القمر ينور السما فى الليل",
                            SoundPath = "/Sound/FiveWord/القمر ينور السما فى الليل.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 136,
                            ImagePath = "/Images/FiveWord/اَلْمُدَرِّسَةُ بتقرأ قصة للأطفال في الفصل.jpg",
                            Label = "اَلْمُدَرِّسَةُ بتقرأ قصة للأطفال في الفصل",
                            SoundPath = "/Sound/FiveWord/اَلْمُدَرِّسَةُ بتقرأ قصة للأطفال في الفصل.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 137,
                            ImagePath = "/Images/FiveWord/المطرب يغنى اغنية فى الحفلة.png",
                            Label = "المطرب يغنى اغنية فى الحفلة",
                            SoundPath = "/Sound/FiveWord/المطرب يغنى اغنية فى الحفلة.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 138,
                            ImagePath = "/Images/FiveWord/الميكانيكي يصلح العربية فى الورشه.png",
                            Label = "الميكانيكي يصلح العربية فى الورشه",
                            SoundPath = "/Sound/FiveWord/الميكانيكي يصلح العربية فى الورشه.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 139,
                            ImagePath = "/Images/FiveWord/الولد يصطاد السمك من البحيرة بالصنارة.png",
                            Label = "الولد يصطاد السمك من البحيرة بالصنارة",
                            SoundPath = "/Sound/FiveWord/الولد يصطاد السمك من البحيرة بالصنارة.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 140,
                            ImagePath = "/Images/FiveWord/الولد يغسل اسنانة بالفرشاة والمعجون.png",
                            Label = "الولد يغسل اسنانة بالفرشاة والمعجون",
                            SoundPath = "/Sound/FiveWord/الولد يغسل اسنانة بالفرشاة والمعجون.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 141,
                            ImagePath = "/Images/FiveWord/الولد يقرأ الكتب فى المكتبة.png",
                            Label = "الولد يقرأ الكتب فى المكتبة",
                            SoundPath = "/Sound/FiveWord/الولد يقرأ الكتب فى المكتبة.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 142,
                            ImagePath = "/Images/FiveWord/الولد يلعب مع اصحابه فى الحديقة.jpg",
                            Label = "الولد يلعب مع اصحابه فى الحديقة",
                            SoundPath = "/Sound/FiveWord/الولد يلعب مع اصحابه فى الحديقة.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 143,
                            ImagePath = "/Images/FiveWord/انا بحب ابويا وامى واختى.png",
                            Label = "انا بحب ابويا وامى واختى",
                            SoundPath = "/Sound/FiveWord/انا بحب ابويا وامى واختى.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 144,
                            ImagePath = "/Images/FiveWord/تشرح اَلْمُدَرِّسَةُ الدروس للأطفال فى المدرسة.jpg",
                            Label = "تشرح اَلْمُدَرِّسَةُ الدروس للأطفال فى المدرسة",
                            SoundPath = "/Sound/FiveWord/تشرح اَلْمُدَرِّسَةُ الدروس للأطفال فى المدرسة.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 145,
                            ImagePath = "/Images/FiveWord/رجل المطافي يطفي الحريق الضخم.png",
                            Label = "رجل المطافي يطفي الحريق الضخم",
                            SoundPath = "/Sound/FiveWord/رجل المطافي يطفي الحريق الضخم.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 146,
                            ImagePath = "/Images/FiveWord/يحمل الفلاح سلة الفواكه والخضراوات.png",
                            Label = "يحمل الفلاح سلة الفواكه والخضراوات",
                            SoundPath = "/Sound/FiveWord/يحمل الفلاح سلة الفواكه والخضراوات.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 147,
                            ImagePath = "/Images/FiveWord/يرسم المهندس خريطة جديدة للمنزل.png",
                            Label = "يرسم المهندس خريطة جديدة للمنزل",
                            SoundPath = "/Sound/FiveWord/يرسم المهندس خريطة جديدة للمنزل.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 148,
                            ImagePath = "/Images/FiveWord/يطبخ الطباخ الطعام فى المطعم.png",
                            Label = "يطبخ الطباخ الطعام فى المطعم",
                            SoundPath = "/Sound/FiveWord/يطبخ الطباخ الطعام فى المطعم.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 149,
                            ImagePath = "/Images/FiveWord/يعالج الطبيب الطفل المريض فى المستشفى.png",
                            Label = "يعالج الدكتور الطفل المريض فى المستشفى",
                            SoundPath = "/Sound/FiveWord/يعالج الدكتور الطفل المريض فى المستشفى.mp3",
                            Type = "FiveWord"
                        },
                        new
                        {
                            Id = 150,
                            ImagePath = "/Images/FiveWord/يكتب الطالب الدرس فى الكراسة.png",
                            Label = "يكتب الطالب الدرس فى الكراسة",
                            SoundPath = "/Sound/FiveWord/يكتب الطالب الدرس فى الكراسة.mp3",
                            Type = "FiveWord"
                        });
                });

            modelBuilder.Entity("DownCare.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Governate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("AppUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DownCare.Core.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DocID");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("DownCare.Core.Entities.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 13, 3, 2, 55, 716, DateTimeKind.Local).AddTicks(7030),
                            IsGroup = true,
                            Name = "MomsGroupChat"
                        });
                });

            modelBuilder.Entity("DownCare.Core.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DiagnosisDate")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MomID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MomID")
                        .IsUnique();

                    b.ToTable("Children");
                });

            modelBuilder.Entity("DownCare.Core.Entities.CommunicationScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<int>("FiveWord")
                        .HasColumnType("int");

                    b.Property<int>("FourWord")
                        .HasColumnType("int");

                    b.Property<int>("OneWord")
                        .HasColumnType("int");

                    b.Property<int>("ThreeWord")
                        .HasColumnType("int");

                    b.Property<int>("TwoWord")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildId")
                        .IsUnique();

                    b.ToTable("CommunicationScore");
                });

            modelBuilder.Entity("DownCare.Core.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MomID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MomID");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("DownCare.Core.Entities.LinguisticsScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<int>("FiveWord")
                        .HasColumnType("int");

                    b.Property<int>("FourWord")
                        .HasColumnType("int");

                    b.Property<int>("OneWord")
                        .HasColumnType("int");

                    b.Property<int>("ThreeWord")
                        .HasColumnType("int");

                    b.Property<int>("TwoWord")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildId")
                        .IsUnique();

                    b.ToTable("LinguisticsScore");
                });

            modelBuilder.Entity("DownCare.Core.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatRoomID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomID");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DownCare.Core.Entities.UserChatRoom", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ChatRoomId");

                    b.HasIndex("ChatRoomId");

                    b.ToTable("UserChatRooms");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "540fa4db-060f-4f1b-b60a-dd199bfe4f0b",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "540fa4db-060f-4f1b-b60a-dd199bfe4111",
                            Name = "Mom",
                            NormalizedName = "MOM"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DownCare.Core.Entities.Doctor", b =>
                {
                    b.HasBaseType("DownCare.Core.Entities.AppUser");

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("DownCare.Core.Entities.Mom", b =>
                {
                    b.HasBaseType("DownCare.Core.Entities.AppUser");

                    b.HasDiscriminator().HasValue("Mom");
                });

            modelBuilder.Entity("DoctorMom", b =>
                {
                    b.HasOne("DownCare.Core.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("DownCare.Core.Entities.Mom", null)
                        .WithMany()
                        .HasForeignKey("MomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DownCare.Core.Entities.Article", b =>
                {
                    b.HasOne("DownCare.Core.Entities.Doctor", "Doctor")
                        .WithMany("Articles")
                        .HasForeignKey("DocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DownCare.Core.Entities.Child", b =>
                {
                    b.HasOne("DownCare.Core.Entities.Mom", "Mom")
                        .WithOne("Child")
                        .HasForeignKey("DownCare.Core.Entities.Child", "MomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mom");
                });

            modelBuilder.Entity("DownCare.Core.Entities.CommunicationScore", b =>
                {
                    b.HasOne("DownCare.Core.Entities.Child", "Child")
                        .WithOne("CommunicationScore")
                        .HasForeignKey("DownCare.Core.Entities.CommunicationScore", "ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("DownCare.Core.Entities.Feedback", b =>
                {
                    b.HasOne("DownCare.Core.Entities.Mom", "Mom")
                        .WithMany("Feedbacks")
                        .HasForeignKey("MomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mom");
                });

            modelBuilder.Entity("DownCare.Core.Entities.LinguisticsScore", b =>
                {
                    b.HasOne("DownCare.Core.Entities.Child", "Child")
                        .WithOne("LinguisticsScore")
                        .HasForeignKey("DownCare.Core.Entities.LinguisticsScore", "ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("DownCare.Core.Entities.Message", b =>
                {
                    b.HasOne("DownCare.Core.Entities.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DownCare.Core.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("ChatRoom");
                });

            modelBuilder.Entity("DownCare.Core.Entities.UserChatRoom", b =>
                {
                    b.HasOne("DownCare.Core.Entities.ChatRoom", "ChatRoom")
                        .WithMany("UserChatRooms")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DownCare.Core.Entities.AppUser", "User")
                        .WithMany("UserChatRooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DownCare.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DownCare.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DownCare.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DownCare.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DownCare.Core.Entities.AppUser", b =>
                {
                    b.Navigation("UserChatRooms");
                });

            modelBuilder.Entity("DownCare.Core.Entities.ChatRoom", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("UserChatRooms");
                });

            modelBuilder.Entity("DownCare.Core.Entities.Child", b =>
                {
                    b.Navigation("CommunicationScore");

                    b.Navigation("LinguisticsScore");
                });

            modelBuilder.Entity("DownCare.Core.Entities.Doctor", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("DownCare.Core.Entities.Mom", b =>
                {
                    b.Navigation("Child");

                    b.Navigation("Feedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
